### ISSUE TITLE
Concept Relevance Propagation

### ISSUE THREAD

**Issue by ghost** [fxnnxc/crp_pytorch#1]
Thank you for your excellent work! Is this code a detailed implementation of the paper 《From “Where” to “What”: Towards Human-Understandable Explanations through Concept Relevance Propagation》. If not, can you provide your paper?

**Comment by leobumjin** [comment]
@Buildernet  

This work is based on the paper 《From “Where” to “What”: Towards Human-Understandable Explanations through Concept Relevance Propagation》. 

Actually, there is an official implementation of the CRP (https://github.com/rachtibat/zennit-crp), but I found that it is quite complex and has dependency on zennit library. Therefore, I've implemented the core concept (masking CNN filters) which could be generalized well and easy to debug for ML researchers🫠

**Comment by ghost** [comment]
@fxnnxc 
thank you for your reply! 
Yes, I noticed the official implementation code of CRP. 
Your work has helped me a lot in understanding the CRP manuscript, thank you!
